### ISSUE TITLE
Add Close Button to Hamburger Menu

### ISSUE THREAD

**Issue by JeetuSuthar** [Ayush215mb/VeerSolutions#3]
Add an "X" or similar icon in the corner of the hamburger menu that serves as a "Close" or "Cancel" button, making it easier for users to navigate on mobile screen.
assign me the task

**Comment by Ayush215mb** [comment]
@JeetuSuthar you are assigned, do the change and send a share the image jere.

**Comment by JeetuSuthar** [comment]
@JeetuSuthar Its done 
While merginf plz add hactober-accepted label 
Thank you

**Comment by JeetuSuthar** [comment]
Heres the image 

![Screenshot 2024-10-31 184322](https://github.com/user-attachments/assets/c74b660c-e109-4956-9caf-8297337bbc08)
